# Configuration

# Which part of the pipeline do you want to execute?
run_tile_creator: 0

run_tile_downloader: 0

run_tile_processor: 0

run_tile_coords_updater: 0

run_registry_creator: 1

# -------- Geocoder --------
# Your Bing API key to geocode addresses
bing_key: AnezE22PWOJH1oOhcQfolc6zSaDrNxfHIgJ8BQ3bh8dH1dovu4UOhSgrRpQIj26J

# -------- Area of interest --------
# Specify the county for which you would like to run the analysis by name.
county: Essen

# -------- Data --------
# DIR where tiles are saved
tile_dir: data/tiles

# Path where pickle with tile coordinates is saved
tile_coords_path: data/coords/Essen.pickle

# Path to shapefile containing rooftop polygons:
rooftop_polygon_path: data/rooftop_polygons/Essen.geojson

# Path to csv where PV locations are stored
pv_db_path: data/pv_database/PV_db.csv

# Path to csv which lists all completely processed tiles
processed_path: logs/processing/Processed.csv

# Path to csv which lists all tiles where processing went wrong
not_processed_path: logs/processing/notProcessed.csv

# Path to csv which lists all downloaded tiles
# Only fully downloaded tiles are stored here
downloaded_path: logs/downloading/DownloadedTiles.csv

# Path to csv which lists all tiles where downloading went wrong
not_downloaded_path: logs/downloading/notDownloadedTiles.csv

# Path to geojson for all German states
german_states_path: data/deutschlandGeoJSON/2_bundeslaender/1_sehr_hoch.geojson

# -------- Model Configuration --------
# Classification threshold
cls_threshold: 0.68

# Segmentation threshold:
seg_threshold: 0.55

# Input resolution for CNN, is fixed for Inception-v3
input_size: 299

# Batch size should be as large as possible to speed up the classification process
batch_size: 10

# -------- Model Checkpoint --------
# Path for loading classification model weights
cls_checkpoint_path: models/classification/inceptionv3_weights.tar

# Path for loading segmentation model weights
seg_checkpoint_path: models/segmentation/deeplabv3_weights.tar